/*
 * Copyright 2014 Stephan Fellhofer
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package it.org.catrobat.jira.adminhelper;

import com.atlassian.selenium.AbstractSeleniumConfiguration;

public class AdminHelperSeleniumConfiguration extends AbstractSeleniumConfiguration {
    @Override
    public String getServerLocation() {
        return "localhost";
    }

    @Override
    public int getServerPort() {
        return 4444;
    }

    @Override
    public String getBrowserStartString() {
        return "";
    }

    @Override
    public String getBaseUrl() {
        return "http://localhost:2990/jira/";
    }

    @Override
    public boolean getStartSeleniumServer() {
        return true;
    }


//    @Override
//    public String getServerLocation() {
//        return "localhost";
//    }
//
//    @Override
//    public int getServerPort() {
//        return 4444;
//    }
//
//    @Override
//    public String getBrowserStartString() {
//        return "";
//    }
//
//    public String getFirefoxProfileTemplate() {
//        return null;
//    }
//
//    @Override
//    public String getBaseUrl() {
//        return "http://localhost:2990/jira/";
//    }
//
//    @Override
//    public boolean getStartSeleniumServer() {
//        return true;
//    }
//
//    public long getActionWait() {
//        return 0;
//    }
//
//    public long getPageLoadWait() {
//        return 0;
//    }
//
//    public long getConditionCheckInterval() {
//        return 0;
//    }
//
//    public boolean getSingleWindowMode() {
//        return false;
//    }
//
//    public String getPerformanceReportLocation() {
//        return null;
//    }
//
//    public boolean getShowAutoGeneratedPerformanceEvents() {
//        return false;
//    }
}
